# Generated by Django 5.1.4 on 2025-01-09 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='in_london',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quoterequestmodel',
            name='state',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='quoterequestmodel',
            name='state_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequestmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='attractiveness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='chasability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='multiplier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='value',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='quoterequestmodel',
            name='date_close',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote_manager.projectmodel')),
            ],
        ),
    ]
