# Generated by Django 5.1.4 on 2025-01-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_manager', '0002_companyblacklist_remove_projectmodel_in_london_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuoteRequestModel',
            new_name='QuoteModel',
        ),
    ]
