# Generated by Django 5.1.4 on 2025-01-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_manager', '0003_rename_quoterequestmodel_quotemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotemodel',
            name='buisness_by',
            field=models.CharField(blank=True, choices=[('karl', 'Karl'), ('scs', 'SCS')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='state',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('incomplete', 'Incomplete'), ('unclaimed', 'Unclaimed'), ('in_progress', 'In progress'), ('waiting_for_supplier', 'Waiting for supplier'), ('waiting_for_client', 'Waiting for client'), ('sent', 'Sent'), ('to_chase', 'To Chase')], default='unknown', max_length=255),
        ),
    ]
