# Generated by Django 4.2.11 on 2024-12-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_file', models.FileField(upload_to='', verbose_name='maxcut_file')),
                ('datetime', models.DateTimeField(verbose_name='upload_datetime')),
                ('msg', models.TextField(verbose_name='generator_message')),
                ('gen_file', models.FileField(upload_to='', verbose_name='generated_file')),
            ],
        ),
    ]
