# Generated by Django 5.1.4 on 2024-12-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcfmodel',
            name='name',
            field=models.CharField(default='Unnamed', max_length=255, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='mcfmodel',
            name='notes',
            field=models.TextField(default='', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='mcfmodel',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='upload_datetime'),
        ),
        migrations.AlterField(
            model_name='mcfmodel',
            name='msg',
            field=models.TextField(default='', verbose_name='generator_message'),
        ),
    ]
