# Generated by Django 5.1.4 on 2024-12-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcfmodel',
            name='filename',
            field=models.CharField(default='bad_name.txt', max_length=255, verbose_name='filename'),
        ),
        migrations.AddField(
            model_name='qfmodel',
            name='filename',
            field=models.CharField(default='bad_name.txt', max_length=255, verbose_name='filename'),
        ),
        migrations.AlterField(
            model_name='mcfmodel',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='qfmodel',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='notes'),
        ),
    ]
