# Generated by Django 5.1.4 on 2024-12-09 14:43

import boq_assistant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq_assistant', '0002_mcfmodel_name_mcfmodel_notes_alter_mcfmodel_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcfmodel',
            old_name='msg',
            new_name='warnings',
        ),
        migrations.AlterField(
            model_name='mcfmodel',
            name='mc_file',
            field=models.FileField(upload_to='', validators=[boq_assistant.models.validate_file_is_csv], verbose_name='maxcut_file'),
        ),
    ]
