# Generated by Django 5.1.4 on 2025-01-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileConvertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion', models.CharField(choices=[('quote_xl_to_maxcut_zip', 'Quote.xlsx to MaxCut_CSVs.zip'), ('maxcut_csv_to_quote_xl', 'MaxCut.csv to Quote.xlsx')], default='quote_xl_to_maxcut_zip', max_length=64)),
                ('upload_file', models.FileField(upload_to='', verbose_name='upload_file')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('filename', models.CharField(default='bad_name.txt', max_length=255, verbose_name='filename')),
                ('gen_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='generated_file')),
                ('warnings', models.TextField(default='', verbose_name='warnings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
